<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProcmonHelper.Contracts\ProcmonHelper.Contracts.csproj" />
    <ProjectReference Include="..\ProcmonHelper.Core\ProcmonHelper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\ExcludeProcmon.pmc" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
